name: CI Pipeline w/ Bicep and Azure What-If + OIDC

on:
  push:
    branches:
      - main


permissions:
  contents: read
  id-token: write

jobs:
  validate-foundation:
    name: Validate Foundation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Bicep
        run: |
          az bicep install
          export PATH=$HOME/.azure/bin:$PATH

      - name: Build Foundation
        run: |
          bicep build ./bicep/foundation/main.bicep \
            --outdir ./bicep/compiled/foundation

  validate-workload:
    name: Validate Workload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Bicep
        run: |
          az bicep install
          export PATH=$HOME/.azure/bin:$PATH

      - name: Build Workload
        run: |
          bicep build ./bicep/workload/main.bicep \
            --outdir ./bicep/compiled/workload

  whatif-foundation:
    name: What-If Foundation
    runs-on: ubuntu-latest
    needs: validate-foundation
    outputs:
      subnetId: ${{ steps.capture-foundation-outputs.outputs.subnetId }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: What-If Foundation
        run: |
          az deployment group what-if \
            --resource-group rg-foundation-dev \
            --template-file ./bicep/foundation/main.bicep

      - name: Capture Foundation Outputs
        run: |
          SUBNET_ID=$(az deployment group show \
          --resource-group rg-foundation-dev \
          --name foundation \
          --query properties.outputs.subnetId.value -o tsv)
          echo "SUBNET_ID=$SUBNET_ID" >> $GITHUB_OUTPUT


  whatif-workload:
    name: What-If Workload
    runs-on: ubuntu-latest
    needs:
      - validate-workload
      - whatif-foundation
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: What-If Workload
        run: |
          az deployment group what-if \
            --resource-group rg-workload-dev \
            --template-file ./bicep/workload/main.bicep \
            --parameters @bicep/workload/parameters.dev.json \
            --parameters subnetId="${{ needs.whatif-foundation.outputs.subnetId }}" \
            --parameters publicIpId='' \
            --parameters adminPassword="${{ secrets.ADMIN_PASSWORD }}"

